### ISSUE TITLE
Required models (checklist for Len)

### ISSUE THREAD

**Issue by TripleHeadedSheep** [TheCyberBrick/The-Betweenlands#315]
This is a checklist for me to see what models I have to make for the coming updates. If you need a model feel free to add it to the list, and give a short description or deadline if required.
If possible, please refer to a related issue.

**Mobs:**
- [x] Stalker
- [x] Pyrad - Dormant #313 
- [x] Swamp Plant #317 
- [x] Chirpsect #317 
- [ ] Jellyfish #317 
- [ ] Big Jellyfish #317 

**Blocks:**
- [x] Purple Pear Crop - Stage 1 - bush
- [x] Purple Pear Crop - Stage 2 - bush
- [x] Purple Pear Crop - Stage 3 - bush
- [x] Purple Pear Crop - Stage 4 - fruit
- [x] Purple Pear Crop - Stage 5 - fruit
- [x] Purple Pear Crop - Stage 6 - fruit
- [x] Purple Pear Crop - Rotten
- [ ] Daytime Extending thing (needs a name, still) #314
- [ ] Pyrad Cocoon - Stage 1 #313 
- [ ] Pyrad Cocoon - Stage 2 #313 
- [ ] Pyrad Cocoon - Stage 3 #313 
- [ ]  Skull Lantern 
- [x] Deeplake Lily #317 

**Items:**
- [x] Weedwood Shield #311 
- [x] Bone Shield #311 
- [x] Syrmorite Shield #311 
- [x] Valonite Shield  #311 
- [x] Lurkerskin Shield #311 
- [x] Lurkerskin Shield - Raft #311 
- [x] Octine Shield #311 
- [x] Dentrothyst Shield (Green and Orange) #311
- [ ] Solid Tar Shield #311
- [ ] Rubber Shield #311
