### ISSUE TITLE
Mob checklist for 1.10 port

### ISSUE THREAD

**Issue by TripleHeadedSheep** [TheCyberBrick/The-Betweenlands#319]
**Passive**
- [x] Blind Cave Fish
- [x] Dragonfly
- [x] Firefly
- [x] Frog
- [x] Gecko
- [x] Harlequin Toad
- [x] Mire Snail
- [x] Sporeling

**Neutral**
- [x] Lurker

**Hostile**
- [x] Angler
- [x] Bloodsnail
- [x] Chiromaw
- [x] Dark Druïd
- [x] Dragonfly
- [x] Gas Cloud
- [x] Leech
- [x] Peat Mummy
- [x] Pyrad
- [x] Silt Crab
- [x] Sludge
- [x] Swamp Hag
- [x] Tar Beast
- [ ] Temple Guardian (Melee)
- [ ] Temple Guardian (Berserker)
- [x] Termite
- [x] Wight

**Boss**
- [ ] Dreadful Peat Mummy
- [ ] Primordial Malevolence

**Utility**
- [x] Tar Minion

**Comment by vadis365** [comment]
Closing as we all are on 1.12.2 now.
