### ISSUE TITLE
New Stuff

### ISSUE THREAD

**Issue by TheCyberBrick** [TheCyberBrick/The-Betweenlands#707]
Mobs:
---
- [x] Spirit Trees (#323)
- [ ] Elder Pyrad (#323)
- [x] Root Sprite
- [ ] Puffin
- [x] Boulder Sprite
- [ ] Chirpsect
- [ ] Anadia
- [ ] New Spoopy Boi?
- [x] Poop Dungeon Mobs - Crypt Crawlers, Worms, etc.
- [x] Stalker
- [ ] Mud Golem

Blocks:
---
- [x] Scabyst building blocks
- [x] Amate Paper Panes
- [x] Nibbletwig Planks + related
- [x] Hearthgrove Planks + related
- [x] Mudpot Candle
- [x] Censer
- [x] Waystones
- [ ] Firefly in Jar
- [ ] Spirit Tree Planks + related (?)
- [x] HL Crystal Ball thing that predicts events
- [ ] Some form of XP storage (or entity?)

Items:
---
- [x] Item Magnet
- [x] Gemstone Singer
- [x] Bone Wayfinder
- [x] Root Pods
- [ ] Strange Alloy + armour and tools
- [x] Dentrothyst Shards
- [x] Amate Paper Map (?)
- [x] Volarkite

World Gen:
---
- [x] Spirit Trees
- [x] Poop Dungeon
- [ ] Ancient Temples

Other:
---
- [ ] Rune stuff?
- [ ] More crops?
- [ ] Other suggestions (#317)
- [ ] Tribes

Adjustments:
---
- [x] Giant Roots as ingrediënts (issue #652)
- [x] Lurker Pouches transfer to chest (issue #653)
- [x] Decreased Slimy Bone Ore gen (issue #654)
- [ ] Reed Rope Leads (issue #655)
- [ ] Other issues
- [x] Rain effect on water
- [ ] Improved armour textures
- [x] Rebalance loot tables

**Comment by levilips123** [comment]
heeeey thats preety good
