### ISSUE TITLE
Minor-issue checklist

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#734]
For _polish._

- [x] The lurker skin pouch goes nutso flickering on the model in the player's inventory. I can't show it very well, but [here's a picture of it in the middle of the legs as "proof".](https://user-images.githubusercontent.com/32495545/47273081-964aeb80-d55c-11e8-8ec8-003362f994cb.png) (it's not ever supposed to be there, btw)
- [x] [The weedwood lever still uses the betweenstone texture, despite it being crafted with a log.](https://user-images.githubusercontent.com/32495545/47273105-f17cde00-d55c-11e8-91c1-938596c5decc.png)
- [x] The scabyst trapdoor uses the wood trapdoor breaking/placing sound instead of the iron one.
- [x] **SUBJECTIVE:** The Angry Betweenstone ruin is way too common. It should be much rarer because (from my understanding) the block itself is supposed to be an easter-egg type thing.
- [x] The lurker skin pouch, bark amulet, and item magnet should all share the same row on the display next to the hotbar.
- [x] [The vanilla attack indicator is completely covered by any of the hotbar display items.](https://user-images.githubusercontent.com/32495545/47273154-c941af00-d55d-11e8-9b86-365fc398d33e.png) Maybe move it over or disable it when there are items equipped with the radial?
- [x] ~~Boulder sprites should have a blacklist of blocks they can't break,~~ and they should be affected by the vanilla `mobGriefing` game rule. They also shouldn't be able to break protected blocks in structures (wight fort, cragrock tower) just because.
- [ ] **SUBJECTIVE:** Peat mummy arms from the ring of summoning are affected by the bark amulet's ability. They can be confused with small hostile mobs like blood snails, smol sludges, and leeches.
- [x] ~~Waystones should deactivate when there's no longer any bone wayfinders linked to them.~~
- [ ] **SUBJECTIVE:** It'd be cooler if you had to right-click on a waystone with a wayfinder that's connected to it in order to deactivate it, instead of throwing it in the crafting grid.
- [ ] The`dungeon_chest_loot` loot-table has the gem singer in both the `dungeon_chest_valuables` pool and the regular one. This seems to make it abundant in dungeon chest loot, e.g., wight forts.

That's all I can think of for now. 

edit: ops i clicked it

**Comment by SamuelBoerlin** [comment]
On the subjective ones:
1) The spawn rate of the large ruin variant was reduced to 1/30th. Is that really still too common? It's not supposd to be super rare, just uncommon I guess.
2) The peat mummy arms are considered alive too and they can be killed, therefore the bark amulet should work for them (e.g. PvP)
3) I don't really agree on that one. It creates the possibility of easily accidentally unlinking your waystone that is thousands of blocks away :P
Do you have a specific reason for this in mind?

**Comment by TheCyberBrick** [comment]
On the subjective ones:

1) The spawn rate of the large ruin variant was reduced to 1/30th. Is that really still too common? It's not supposd to be super rare, just uncommon I guess.
2) The peat mummy arms are considered alive too and they can be killed, therefore the bark amulet should work for them (e.g. PvP) Edit: Actually I don't know if they work against other players :thinking:
3) I don't really agree on that one. It creates the possibility of easily accidentally unlinking your waystone that is thousands of blocks away :P
Do you have a specific reason for this in mind?

**Comment by PetasiGit** [comment]
I ran around a test world and found at least two of it in every marsh. I feel it should be at least 1/100. Obviously, I'm not part of your team so I don't know how you guys feel about it, but I think the Angry Betweenstone block should be the rarest block in the entire dimension because it's an easter-egg with your logo on it. Think of it like a trophy block.

As I said, it's subjective. If you like configs, you could add a white/blacklist for it; but it's not that important to me; just something I noticed.

Maybe my description is unclear or I'm misunderstanding what you said. I think the player should physically go to the waystone to unlink it through an interaction instead of being able to unlink it from whereever they want. It just feels less immersive the way it is now. You unlink it by... crafting it? You decide.

**Comment by TheCyberBrick** [comment]
>This seems to make it abundant in dungeon chest loot, e.g., wight forts.

Did you test that? My results: 23 gem singer in 20 fortresses -> ~1.15 gem singers per Fortress. Seems reasonable to me. In all fortresses I found at most two gem singers except for one where I found 8, and that's just how randomness works.
Keep in mind that the drop rate is very low in the non-valuables table: ~1.2%

**Comment by PetasiGit** [comment]
>Did you test that? ... except for one where I found 8, and that's just how randomness works.

Maybe I just got lucky that way. I found at least 5 in one and 4 in another. :P

**Comment by TheCyberBrick** [comment]
Hm yeah, that's just how it is 🤷‍♂️ 
If we wanted more consistent loot we'd have to redo how loot works. E.g. instead of having loot tables per chest, have a structure loot pool for the whole structure and whenever a chest is opened the first time it pulls loot from the structure loot pool according to the loot tables' rules.

**Comment by TheCyberBrick** [comment]
@okl1001 https://github.com/Angry-Pixel/The-Betweenlands/issues/756
